[package]
name = "simple-wifi-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "simple_wifi_config"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
wifi-config = "0.1.0"
